//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Song_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionPermissionRole
    {
        public int Id { get; set; }
        public int ActionPermissionId { get; set; }
        public int RoleId { get; set; }
    
        public virtual ActionPermission ActionPermission { get; set; }
        public virtual Role Role { get; set; }
    }
}
