//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Song_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuPermission
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MenuPermission()
        {
            this.MenuPermissionRole = new HashSet<MenuPermissionRole>();
        }
    
        public int Id { get; set; }
        public string ActionName { get; set; }
        public string ControllerName { get; set; }
        public string Description { get; set; }
        public string IconName { get; set; }
        public string IconPath { get; set; }
        public string Name { get; set; }
        public int ParentId { get; set; }
        public string TreeCode { get; set; }
        public bool LEAF { get; set; }
        public bool IsMainPage { get; set; }
        public int OrderValue { get; set; }
        public System.DateTime CreateTime { get; set; }
        public bool IsAbort { get; set; }
        public Nullable<int> NodeLevel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MenuPermissionRole> MenuPermissionRole { get; set; }
    }
}
